apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-b

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: school-b
  target:
    kind: Deployment

commonLabels:
  tenant: school-b

configMapGenerator:
- name: tenant-config
  behavior: merge
  literals:
  - TENANT_SLUG=school-b
  - TENANT_NAME="Greenwood Institute"
