apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_32_CHARS_MIN"
  JWT_REFRESH_SECRET: "CHANGE_ME_32_CHARS_MIN"
  REDIS_PASSWORD: ""
  AWS_S3_ACCESS_KEY: "CHANGE_ME"
  AWS_S3_SECRET_KEY: "CHANGE_ME"
