apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "school-erp.fullname" . }}-sa
  labels:
    {{- include "school-erp.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/school-erp-s3-role"
